mongo:
  host:         localhost
  port:         27017
  db:           music
  collection:   tracks

paths:
#  music:        /tomato/media/music/The Beatles/
#  music:        /tomato/media/music/Amy Winehouse/2007-03-13 - Back to Black/
#  music:        /tomato/media/music/Amy Winehouse/
  music:        /tomato/media/music/

